spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
logging:
  level:
    com.codeit.project.deokhugam: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace