server:
  port: 80

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: ${TZ}
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

aws:
  accessKeyId: ${AWS_S3_ACCESS_KEY}
  secretKey: ${AWS_S3_SECRET_KEY}
  region: ${AWS_S3_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    prefix: uploads

app:
  cdn:
    base-url: ${CDN_URL}
logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    org.springframework.web: info

management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: false