spring:
  application:
    name: deokhugam
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always

external:
  naver:
    api:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}

info:
  name: Deokhugam
  version: 1.0.0
  java:
    version: 17
  spring-boot:
    version: 3.5.6
  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    storage:
      type: ${discodeit.storage.type}
      path: ${discodeit.storage.local.root-path}
    multipart:
      max-file-size: ${spring.servlet.multipart.maxFileSize}
      max-request-size: ${spring.servlet.multipart.maxRequestSize}

