spring:
  application:
    name: deokhugam
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always

file:
  upload-dir: ${FILE_UPLOAD_DIR:/app/uploads}

info:
  name: Deokhugam
  version: 1.0.0
  java:
    version: 17
  spring-boot:
    version: 3.5.6
  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    multipart:
      max-file-size: ${spring.servlet.multipart.maxFileSize}
      max-request-size: ${spring.servlet.multipart.maxRequestSize}

external:
  naver:
    api:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
  ncp:
    api:
      invoke-url: ${NCP_INVOKE_URL}
      secret-key: ${NCP_CLIENT_SECRET}