spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/deokhugam
    username: deokhugam
    password: deokhugam1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: ${TZ}
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

aws:
  accessKeyId: ${AWS_S3_ACCESS_KEY}
  secretKey: ${AWS_S3_SECRET_KEY}
  region: ${AWS_S3_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    prefix: uploads

app:
  cdn:
    base-url: ${CDN_URL}
logging:
  level:
    com.codeit.project.deokhugam: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true