-- CREATE USER deokhugam_user WITH ENCRYPTED PASSWORD 'user1234';
-- GRANT deokhugam_user TO postgres;
-- CREATE DATABASE deokhugam OWNER deokhugam_user;

DROP TABLE IF EXISTS review_likes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS ranks;

CREATE TABLE users
(
    id         BIGSERIAL PRIMARY KEY,
    email      VARCHAR(300) UNIQUE      NOT NULL,
    nickname   VARCHAR(50) UNIQUE       NOT NULL,
    password   VARCHAR(300)             NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);

CREATE TABLE books
(
    id            BIGSERIAL PRIMARY KEY,
    title         VARCHAR(256),
    author        VARCHAR(256),
    description   VARCHAR(1024),
    publisher     VARCHAR(256),
    published_at  date,
    isbn          VARCHAR(1024),
    thumbnail_url VARCHAR(1024),
    created_at    timestamp with time zone NOT NULL,
    updated_at    timestamp with time zone,
    deleted_at    timestamp with time zone
);

CREATE TABLE reviews
(
    id         BIGSERIAL PRIMARY KEY,
    user_id    BIGINT                   NOT NULL,
    book_id    BIGINT                   NOT NULL,
    content    VARCHAR(1024),
    rating     INT                      NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT fk_reviews_book FOREIGN KEY (book_id)
        REFERENCES books (id),
    CONSTRAINT unique_book_user UNIQUE (book_id, user_id)
);

CREATE TABLE review_likes
(
    id         BIGSERIAL PRIMARY KEY,
    review_id  BIGINT                   NOT NULL,
    user_id    BIGINT                   NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT fk_review_likes_review FOREIGN KEY (review_id)
        REFERENCES reviews (id),
    CONSTRAINT fk_review_likes_user FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT unique_review_user UNIQUE (review_id, user_id)
);

CREATE TABLE comments
(
    id         BIGSERIAL PRIMARY KEY,
    review_id  BIGINT                   NOT NULL,
    user_id    BIGINT                   NOT NULL,
    content    VARCHAR(1024),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT fk_comments_review FOREIGN KEY (review_id)
        REFERENCES reviews (id),
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id)
        REFERENCES users (id)
);

CREATE TABLE notifications
(
    id         BIGSERIAL PRIMARY KEY,
    review_id  BIGINT                   NOT NULL,
    user_id    BIGINT                   NOT NULL,
    type       VARCHAR(20),
    content    VARCHAR(1024),
    confirmed  BOOLEAN DEFAULT false,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT fk_notifications_review FOREIGN KEY (review_id)
        REFERENCES reviews (id),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id)
        REFERENCES users (id)
);

CREATE TABLE ranks
(
    id         BIGSERIAL PRIMARY KEY,
    target     VARCHAR(20)              NOT NULL,
    target_id  BIGINT,
    type       VARCHAR(20),
    rank_no    INT,
    score      DECIMAL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone
);

COMMENT
ON COLUMN notifications.type IS 'REVIEW_LIKED, REVIEW_COMMENTED, REVIEW_RANKED';
COMMENT
ON COLUMN ranks.type IS '일간(DAILY) 주간(WEEKLY) 월간(MONTHLY) 역대(ALL_TIME)';
COMMENT
ON COLUMN ranks.target IS 'BOOK REVIEW USER';

ALTER TABLE books ALTER COLUMN title SET DATA TYPE text COLLATE "ko_KR.utf8";

-- Autogenerated: do not edit this file

DROP TABLE IF EXISTS BATCH_JOB_INSTANCE;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT;

CREATE TABLE BATCH_JOB_INSTANCE  (
                                     JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
                                     VERSION BIGINT ,
                                     JOB_NAME VARCHAR(100) NOT NULL,
                                     JOB_KEY VARCHAR(32) NOT NULL,
                                     constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION  (
                                      JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
                                      VERSION BIGINT  ,
                                      JOB_INSTANCE_ID BIGINT NOT NULL,
                                      CREATE_TIME TIMESTAMP NOT NULL,
                                      START_TIME TIMESTAMP DEFAULT NULL ,
                                      END_TIME TIMESTAMP DEFAULT NULL ,
                                      STATUS VARCHAR(10) ,
                                      EXIT_CODE VARCHAR(2500) ,
                                      EXIT_MESSAGE VARCHAR(2500) ,
                                      LAST_UPDATED TIMESTAMP,
                                      constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
                                          references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
                                             JOB_EXECUTION_ID BIGINT NOT NULL ,
                                             PARAMETER_NAME VARCHAR(100) NOT NULL ,
                                             PARAMETER_TYPE VARCHAR(100) NOT NULL ,
                                             PARAMETER_VALUE VARCHAR(2500) ,
                                             IDENTIFYING CHAR(1) NOT NULL ,
                                             constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
                                                 references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION  (
                                       STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
                                       VERSION BIGINT NOT NULL,
                                       STEP_NAME VARCHAR(100) NOT NULL,
                                       JOB_EXECUTION_ID BIGINT NOT NULL,
                                       CREATE_TIME TIMESTAMP NOT NULL,
                                       START_TIME TIMESTAMP DEFAULT NULL ,
                                       END_TIME TIMESTAMP DEFAULT NULL ,
                                       STATUS VARCHAR(10) ,
                                       COMMIT_COUNT BIGINT ,
                                       READ_COUNT BIGINT ,
                                       FILTER_COUNT BIGINT ,
                                       WRITE_COUNT BIGINT ,
                                       READ_SKIP_COUNT BIGINT ,
                                       WRITE_SKIP_COUNT BIGINT ,
                                       PROCESS_SKIP_COUNT BIGINT ,
                                       ROLLBACK_COUNT BIGINT ,
                                       EXIT_CODE VARCHAR(2500) ,
                                       EXIT_MESSAGE VARCHAR(2500) ,
                                       LAST_UPDATED TIMESTAMP,
                                       constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
                                           references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
                                               STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                               SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                               SERIALIZED_CONTEXT TEXT ,
                                               constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
                                                   references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
                                              JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                              SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                              SERIALIZED_CONTEXT TEXT ,
                                              constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
                                                  references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;